services:

  backend:
    container_name: backend
    build:
      context: .
    networks:
      - internal_network
    ports:
      - 127.0.0.1:8000:8000

  web:
    container_name: web
    image: nginx
    networks:
      - internal_network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - ./nginx/privkey.pem:/etc/ssl/private/privkey.pem
    ports:
    - '80:80'
    - '443:443'

networks:
  internal_network:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
